### ISSUE TITLE
Please do add installing and how to run program instructions in readme.md

### ISSUE THREAD

**Issue by RavinderSingh13-git** [Nillipilli/Sudoku_Game#1]
Hello @Nillipilli ,

First of all Congrats and Well done for creating this nice project. Just 2 points for very small improvement new users who are learning python like myself, you could do add 2 commands into your readme.MD file.

```
pip install py-sudoku
pip install tk
```
That will complete your readme file, cheers and happy learning.

**Comment by Nillipilli** [comment]
Thanks for the nice words and your suggestion. :)
I added a 'how to run' to the readme.
